### PR TITLE
Added support for reading files in the ows_geopackage extension

### PR DESCRIPTION
**Pull request by doublebyte1**
- Files can be read using, either the qgis_geopackage or the ows_geopackage extensions.
- Currently, writing is only supported using the qgis_geopackage extension.

### CODE REVIEW

**Comment by pka** [comment]
Thanks for the pull request, Joana!
Could you please "merge" the Readme and metadata.txt as well?

**Comment by doublebyte1** [comment]
@pka @pvgenuchten a "merged" readme and metadata.txt were added in my last commits. I also added an "about" dialog to the plugin.

**Comment by pka** [comment]
I've merged into master, but wasn't able to test yet. I'll test, polish and release next week.

**Comment by doublebyte1** [comment]
@pka I just realized that the qgis library (qgisgpkg/qgpkg.py) needs to remain unchanged, in order to support the cli for the qgis_geopackage extension. I reverted to your [last commit](https://github.com/GeoCat/qgpkg/commit/63f16845c00f630958563a7ed378a5ea594a813a). I did not have time to test, but please let me know if it works.

**Pull request closed without merging**
